server:
  port: 8082
spring:
  application:
    name: "autenticacion"
  r2dbc:
    pool:
      enabled: false
  devtools:
    add-properties: false
  profiles:
    include: null
adapters:
  r2dbc:
    host: "${MYSQL_HOST:localhost}"
    port: "${MYSQL_PORT:3306}"
    database: "${MYSQL_DATABASE:autenticacion}"
    username: "${MYSQL_USER:myuser}"
    password: "${MYSQL_PASSWORD:mypassword}"
    ssl-enabled: "${MYSQL_SSL_ENABLED:true}"
routes:
  paths:
    registrar: "/api/v1/usuarios"

    validar: "/api/v1/validar"

    login: "/api/v1/login"

    salario: "/api/v1/salario"

security:
  jwt:
    secret: ${JWT_SECRET:my-super-secret-key-1234567890abcdef}
    expiration: ${JWT_EXPIRATION:3600000}


management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins:

  - ${GATEWAY:http://localhost:8080}
springdoc:
  swagger-ui:
    url: /v3/api-docs
    path: /swagger-ui.html
    enabled: true
    disable-swagger-default-url: true
    config-url: /v3/api-docs/swagger-config
    urls-primary-name: Mi API